wandb_version: 1

confidence_threshold:
  desc: null
  value: 0.15
model:
  desc: null
  value: yolov8n
tracker:
  desc: null
  value: ByteTrack
prediction_method:
  desc: null
  value: Kalman Filter
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1771428009
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
